taskkill /F /IM UniversalPauseButton.exe
taskkill /F /IM MonsterHunterWorld.exe
taskkill /F /IM MonsterHunterRise.exe
taskkill /F /IM game.exe
taskkill /F /IM SkyrimSE.exe
taskkill /F /IM steam.exe
taskkill /F /IM steamwebhelper.exe
taskkill /F /IM IDMan.exe
taskkill /F /IM IEMonitor.exe
taskkill /F /IM Teams.exe
